const USER_ROLES = {
  USER_MANAGER: "USER_MANAGER",
  DISTRIBUTOR_MANAGER: "DISTRIBUTOR_MANAGER",
  INVENTORY_MANAGER: "INVENTORY_MANAGER",
  SUPPLIER_CHAIN_SUPERVISOR: "SUPPLIER_CHAIN_SUPERVISOR",
  EXPORT_MANAGER: "EXPORT_MANAGER",
  DONATION_MANAGER: "DONATION_MANAGER",
  SHOWROOM_AND_SALES_MANAGER: "SHOWROOM_AND_SALES_MANAGER",
  DISTRIBUTORS: "DISTRIBUTORS",
};

module.exports = USER_ROLES;
